services:
  # smart-charging-api:
  #   container_name: smart-charging-api
  #   build:
  #     context: .
  #     dockerfile: ./source/SmartCharging.Api/Dockerfile
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - smartcharging
  #   depends_on:
  #     - redis
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04"
    environment:
      SA_PASSWORD: "sa"
      ACCEPT_EULA: "Y"
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - smart-charging-api
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - smart-charging-api
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - smart-charging-api
networks:
  smart-charging-api:
    driver: bridge
volumes:
  redis-data:
  elasticsearch-data:
